# Generated by Django 4.0.4 on 2022-06-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
