# Generated by Django 4.0.4 on 2022-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
