# Generated by Django 4.0.4 on 2022-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_course_code_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
